# Generated by Django 2.0.6 on 2020-04-08 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fofa', '0002_auto_20200408_2119'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='albumindex',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='albumlist',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='articlelist',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='countnum',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='dashi',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='homework',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'managed': False},
        ),
    ]
