# Generated by Django 2.0.6 on 2020-04-09 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fofa', '0003_auto_20200408_2121'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin',
            options={},
        ),
        migrations.AlterModelOptions(
            name='albumindex',
            options={},
        ),
        migrations.AlterModelOptions(
            name='albumlist',
            options={},
        ),
        migrations.AlterModelOptions(
            name='articlelist',
            options={},
        ),
        migrations.AlterModelOptions(
            name='countnum',
            options={},
        ),
        migrations.AlterModelOptions(
            name='dashi',
            options={},
        ),
        migrations.AlterModelOptions(
            name='homework',
            options={},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
    ]
