# Generated by Django 2.0.6 on 2020-04-09 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fofa', '0004_auto_20200409_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='albumindex',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='fofa.AlbumList'),
        ),
        migrations.AddField(
            model_name='articlelist',
            name='dashi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='fofa.Dashi'),
        ),
        migrations.AddField(
            model_name='countnum',
            name='homework',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='fofa.Homework'),
        ),
        migrations.AddField(
            model_name='homework',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='fofa.User'),
        ),
    ]
