# Generated by Django 2.0.6 on 2020-04-09 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fofa', '0005_auto_20200409_0931'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='albumindex',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='albumlist',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='articlelist',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='countnum',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='dashi',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='homework',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'managed': False},
        ),
    ]
