# Generated by Django 2.0.6 on 2020-04-10 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=20, null=True)),
                ('fa_name', models.CharField(blank=True, max_length=20, null=True)),
                ('passeord', models.CharField(blank=True, max_length=50, null=True)),
                ('salt', models.CharField(blank=True, max_length=20, null=True)),
                ('gender', models.CharField(blank=True, max_length=5, null=True)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('e_mail', models.CharField(blank=True, max_length=30, null=True)),
                ('personal_brief', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='pic')),
                ('status', models.IntegerField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('register_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
