# Generated by Django 2.0.6 on 2020-04-08 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutoImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='pic')),
                ('image_decoration', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('upload_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'auto_image',
            },
        ),
    ]
