# Generated by Django 2.0.6 on 2020-04-08 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autoimage',
            options={'managed': False},
        ),
    ]
