# Generated by Django 2.0.6 on 2020-04-09 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0002_auto_20200408_2121'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autoimage',
            options={},
        ),
    ]
