# Generated by Django 2.0.6 on 2020-04-09 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0003_auto_20200409_0929'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autoimage',
            options={'managed': False},
        ),
    ]
